@protocol = http
@hostname = https://meiaservicestst.awqaf.gov.qa/eProjects/api
@port = :3000
@host = {{hostname}}{{port}}

@contentType = application/json

### Post projects
POST {{hostname}}read/projects
Content-Type:{{contentType}}

{
    "PROJECT_ID": 1,
    "PROJECT": "مشروع إفطار صائم",
    "IS_ACTIVE": 1
}

### Post projects_members
POST {{hostname}}/read/projects_members
Content-Type:{{contentType}}

{
    "FISCAL_YEAR_ID": 20,
    "PROJECT_ID": 1,
    "IS_ACTIVE": 1
}

### Post projects_customers
POST {{hostname}}/read/projects_customers
Content-Type:{{contentType}}

{
    "FISCAL_YEAR_ID": 20,
    "PROJECT_ID": 1,
    "IS_ACTIVE": 1
}

### Post items
POST {{hostname}}/read/items
Content-Type:{{contentType}}

{
    "GROUP_ID": 1,
    "ITEM_ID": 1,
    "IS_ACTIVE": 1
}

### Post customers locations items
POST {{hostname}}/read/customers_locations_items
Content-Type:{{contentType}}

{
    "FISCAL_YEAR_ID": 20,
    "PROJECT_ID": 1,
    "CUSTOMER_ID": 1
}

### Post supply orders
POST {{hostname}}/read/supply_orders

### Post locations
POST {{hostname}}/read/locations

### Post cities
POST {{hostname}}/read/cities
Content-Type:{{contentType}}

{
    "CITY_ID": 1,
    "CITY": "الدوحة"
}

### Post zones
POST {{hostname}}/read/zones
Content-Type:{{contentType}}

{
    "CITY_ID":1
}