const env = process.env;

const db = {
  user: env.DB_USER,
  password: env.DB_PASSWORD,
  connectString : env.DB_CONNECTION_STRING,
  //edition: 'e2'
};

module.exports = db;

//DB_USER=WQTENDERS_NEW
//DB_PASSWORD=WQTENDERS
//DB_CONNECTION_STRING=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST= 172.16.251.105)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=WQFPROD)))
//DB_CONNECTION_STRING=(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP) (HOST = AWQORADEV) (PORT = 1521)) (CONNECT_DATA = (SERVICE_NAME = WQFCLONE)))

